# Generated by Django 5.1.4 on 2025-01-08 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='danh_muc/')),
            ],
            options={
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbs.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_giao', 'Đang giao'), ('da_giao', 'Đã giao'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20)),
                ('dia_chi_giao_hang', models.TextField()),
                ('trang_thai_thanh_toan', models.BooleanField(default=False)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbs.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mo_ta', models.TextField(blank=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san_pham/')),
                ('so_luong_ton', models.IntegerField(default=0)),
                ('thuong_hieu', models.CharField(max_length=100)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hoat_dong', models.BooleanField(default=True)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbs.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbs.giohang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbs.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbs.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbs.sanpham')),
            ],
        ),
    ]
